name: Update awesome list

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: 30 0 * * 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Awesome generator
        uses: simonecorsi/mawesome@v2
        with:
          api-token: ${{ secrets.GITHUB_TOKEN }}
          template-path: 'template/README.ejs'
